### ISSUE TITLE
Okay to refer to this macro?

### ISSUE THREAD

**Issue by SchmidtPaul** [istvank/Citavi-Macros#1]
Hi there,
while working on my R-package [CitaviR](https://schmidtpaul.github.io/CitaviR/index.html) I stumbled upon your macro. Since the approach in that macro seems quite similar to one of the package's functions, I'd like to mention your macro in a side note of the documentation. I just put it at the end of [this section](https://schmidtpaul.github.io/CitaviR/articles/obv_pot_dups.html#details-1) in the grey box. 

I just wanted to ask if this is okay with you. You could even create a pull request if you want to rephrase it [here](https://github.com/SchmidtPaul/CitaviR/blob/ff030637ef5ebb61671940fd7ecda9f527aff604/vignettes/obv_pot_dups.Rmd#L138).

Cheers

**Comment by istvank** [comment]
Hi Paul,

sure, feel free to mention it, and if you find anything that you would do better, please contact me or better raise an issue.

I looked at your project and allow me one comment: I would suggest you not to work on Excel, but on the Citavi database itself. You can simply open a Citavi file and work on it as Sqlite. That's what I am doing in other projects. For cloud projects, I export/save it as local project and then continue.

Cheers!

**Comment by SchmidtPaul** [comment]
Cool. Thanks a lot for the input - I really wasn't aware that I could access the Citavi database itself :astonished: I will now throw myself at it. I have the feeling that using [RSQLite](https://db.rstudio.com/databases/sqlite/) I may even be able boil it down to only Citavi and R.

**Comment by SchmidtPaul** [comment]
Hi, just wanted to thank you again for your input. I was able to make it work and downgraded the old Excel approach to an alternative approach, while putting the focus on the new approach. Thanks to already existing implementations in R, I actually don't even need Sqlite or any other software to [read](https://schmidtpaul.github.io/CitaviR/reference/read_Citavi_ctv6.html) or [update](https://schmidtpaul.github.io/CitaviR/reference/update_Citavi_ctv6.html) local Citavi projects via R.

https://schmidtpaul.github.io/CitaviR/articles/CitaviR.html

**Comment by istvank** [comment]
Awesome! Do you have any feedback from Citavi, whether this approach (programmatically accessing the Citavi database) somehow violates any of their licenses? I have various tooling to visualize Citavi, but I'm too cautious to publish them.

**Comment by SchmidtPaul** [comment]
Well not particularly on this approach, but
  
  1. they seemed super nice and open when I asked about creating my package and using their logo and name [here](https://help.citavi.com/topic/164019-r-package-citavir) (but yeah, I did not mention programmatically accessing the Citavi database then)
  2.   I thought I had once read something about this in their manual, but right now I can only find this small bullet point [here](https://www1.citavi.com/sub/manual6/en/index.html?feature_overview.html), which is at best making a suggestion: "Projects are saved in the SQLite database format **(unencrypted)**."

But I think I will just ask them.

**Comment by istvank** [comment]
Btw., here is a short glimpse of how I am using the Citavi database: Visualizing Citavi categories, the categorized papers, as well as their co-citations:
<img width="1072" alt="3D Force Graph Visualization" src="https://user-images.githubusercontent.com/741780/114711846-b758b580-9d2f-11eb-9556-94137f98f69f.png">

It really helps visually clustering the references, in particular because in our group we have around 25.000 categorized entries in our Citavi. 🤯
Would be interesting to get their take on accessing SQLite directly.

**Comment by SchmidtPaul** [comment]
Here's their reply: 
https://help.citavi.com/topic/174771-auf-die-datenbank-von-lokalen-projekten-via-sqlite-zugreifen-lizenzbestimmungen

So I'm taking away from it that there is no licensing issue with any of it. However, they would be thankful if no changes in the databank would be made because these can lead to problems which end up getting posted in their support forum.

**Comment by istvank** [comment]
That's cool, thanks for asking!
Haha, 
> (...) weil Probleme, die dabei entstehen erfahrungsgemäß bei uns im Support ankommen.

so we're not the only ones. 😀
That's exactly why the changes through duplicate detection in this repo are done via Macro.
